#!/bin/sh

# paths
# --
# (c) Iver!
# Iván Jaimes <iver@iver.mx>
#

# This is the user path enviroment file for GNU/Linux.
# See bash_rc or bash_profile for more information.

# input mode
umask 0007
WORKSPACE=${HOME};

localpaths () {
  LPATH=${PATH}

  # binaries
  [ -d /usr/sbin ] && LPATH=/usr/sbin:${LPATH}
  [ -d /usr/bin ] && LPATH=/usr/bin:${LPATH}
  [ -d /sbin ] && LPATH=/sbin:${LPATH}
  [ -d /bin ] && LPATH=/bin:${LPATH}

  # locals
  [ -d /usr/local/bin ] && LPATH=/usr/local/bin:${LPATH}
  [ -d /opt/local/sbin ] && LPATH=/opt/local/sbin:${LPATH}
  [ -d /opt/local/bin ] && LPATH=/opt/local/bin:${LPATH}
  [ -d ${HOME}/apps ] && LPATH=${HOME}/apps:${LPATH}
  [ -d ${HOME}/bin ] && LPATH=${HOME}/bin:${LPATH}
  [ -d /usr/local/sbin/ ] && LPATH=/usr/local/sbin:${LPATH}

  LPATH=.:${LPATH}
  PATH=${LPATH}
}


go_path() {
  [[ -s "/usr/bin/go" ]] && export GOROOT=/usr/bin/go;
  [ -d ${WORKSPACE}/go ] && export GOPATH=${WORKSPACE}/go;
  [ -d /usr/local/go/bin ] && export GOBIN=/usr/local/go/bin;
  [ -d ${GOBIN} ] && PATH=${PATH}:${GOBIN};
}

localpaths
go_path

